require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExpensesController do

 before(:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
    @user2 = FactoryGirl.create(:user)
  end
  let(:your_expense) { FactoryGirl.create(:expense, user: @user2) }
  let(:my_expense) { FactoryGirl.create(:expense, user: @user) }

  # This should return the minimal set of attributes required to create a valid
  # Expense. As you add validations to Expense, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExpensesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all of my expenses as @expenses" do
      get :index, {}
      assigns(:expenses).should eq([my_expense])
    end
    it "does not show expenses that are not mine" do
      get :index, {}
      assigns(:expenses).should_not include(your_expense)
    end
  end

  describe "GET show" do
    it "assigns the requested expense as @expense" do
      get :show, {:id => my_expense.to_param}
      assigns(:expense).should eq(my_expense)
    end
    it "redirects to index if I'm not allowed to see the expense" do
      get :show, {id: your_expense.to_param}
      response.should redirect_to(expenses_path)
    end
  end

  describe "GET new" do
    it "assigns a new expense as @expense" do
      get :new, {}
      assigns(:expense).should be_a_new(Expense)
    end
  end

  describe "GET edit" do
    it "assigns the requested expense as @expense" do
      get :edit, {:id => my_expense.to_param}
      assigns(:expense).should eq(my_expense)
    end
    it "redirects to index if I'm not allowed to see the invoice" do
      get :edit, {:id => your_expense.to_param}
      response.should redirect_to(expenses_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Expense" do
        my_invoice = my_expense.invoice
        expect {
          post :create, {:expense => {invoice_id: my_invoice.to_param, rate: 100, time: 4, task: "Dancing"}}
        }.to change(Expense, :count).by(1)
      end

      it "assigns a newly created expense as @expense" do
        post :create, {:expense => {invoice_id: my_expense.invoice.to_param, rate: 100, time: 4, task: "Dancing"}}
        assigns(:expense).should be_a(Expense)
        assigns(:expense).should be_persisted
      end

      it "redirects to the created expense" do
        post :create, {:expense => {invoice_id: my_expense.invoice.to_param, rate: 100, time: 4, task: "Dancing"}}
        response.should redirect_to(Expense.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expense as @expense" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expense.any_instance.stub(:save).and_return(false)
        post :create, {:expense => {  }}
        assigns(:expense).should be_a_new(Expense)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expense.any_instance.stub(:save).and_return(false)
        post :create, {:expense => {  }}
        response.should render_template("new")
      end
    end

    it "does not save an expense for an invoice that is not associated with me" do
      post :create, {:expense => {invoice_id: your_expense.invoice.to_param, title: "Attending Concerts"}}
      assigns(:expense).should_not be_persisted
    end
  end

  describe "PUT update" do
    describe "when it is owned by me" do
      describe "with valid params" do
        it "updates the requested expense" do
          Expense.any_instance.should_receive(:update).with({ "task" => "gathering llamas" })
          put :update, {:id => my_expense.to_param, :expense => {"task" => "gathering llamas" }}
        end

        it "assigns the requested expense as @expense" do
          put :update, {:id => my_expense.to_param, :expense => valid_attributes}
          assigns(:expense).should eq(my_expense)
        end

        it "redirects to the expense" do
          put :update, {:id => my_expense.to_param, :expense => valid_attributes}
          response.should redirect_to(my_expense)
        end
      end

      describe "with invalid params" do
        it "assigns the expense as @expense" do
          Expense.any_instance.stub(:save).and_return(false)
          put :update, {:id => my_expense.to_param, :expense => {  }}
          assigns(:expense).should eq(my_expense)
        end

        it "re-renders the 'edit' template" do
          Expense.any_instance.stub(:save).and_return(false)
          put :update, {:id => my_expense.to_param, :expense => {  }}
          response.should render_template("edit")
        end
      end
    end
    describe "when it is not owned by me" do
      it "reredirects to the index page" do
        put :update, {:id => your_expense.to_param, :invoice => {  }}
        response.should redirect_to(expenses_path)
      end
    end
  end

  describe "DELETE destroy" do
    describe "when it is associated with me" do
      it "destroys the requested expense" do
        expense = Expense.create! invoice_id: my_expense.invoice.to_param
        expect {
          delete :destroy, {:id => expense.to_param}
        }.to change(Expense, :count).by(-1)
      end

      it "redirects to the expenses list" do
        expense = Expense.create! invoice_id: my_expense.invoice.to_param
        delete :destroy, {:id => expense.to_param}
        response.should redirect_to(expenses_url)
      end
    end
    describe "when it is not associated with me" do
      it "does not destroy the requested expense" do
        expense = Expense.create! invoice_id: your_expense.invoice.id
        expect {
          delete :destroy, {:id => expense.to_param}
        }.to change(Expense, :count).by(0)
      end
      it "redirects to the expenses index path" do
        delete :destroy, {:id => your_expense.to_param}
        response.should redirect_to(expenses_url)
      end
    end
  end

end
